version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5671:5671"  # SSL port
      - "15671:15671"  # SSL management port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./ssl:/etc/rabbitmq/ssl
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    restart: always

volumes:
  rabbitmq_data:
